apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template: 
    metadata:
      labels:
        component: web
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: client
          image: leandrosoares/multi-client
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000